### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by louanfontenele** [xincan1949/lovely-mindmap#10]
Hello, the Plugin is not working in the new version.

**Comment by louanfontenele** [comment]
I'm also using Windows.

**Comment by shaunhurryup** [comment]
Thanks for your feedback! I've tested the plugin on my Windows 11 and Mac M1, and they run smoothly. Could you provide more details about the issue you're facing? For instance, any uncaught errors shown in the developer tools would be helpful for troubleshooting. Alternatively, describing the action you expected versus the actual outcome would also be beneficial.

**Comment by facundobianco** [comment]
Hi, same issue here in MBP M2 Sonoma 14.4. It's my first time using Lovely-Mindmap and cannot be able to perform any action.

And Obsidian is v1.5.8.

Thanks in advance.

**Comment by vecyang1** [comment]
Same here not working 

About Obsidian
Version 1.5.11 (Installer 1.5.11)


<img width="280" alt="image" src="https://github.com/shaunhurryup/lovely-mindmap/assets/130784544/8cc139f3-5b3c-4afc-abe7-756c1e092f38">

**Comment by vecyang1** [comment]
The [tab] is not working. [Enter] is working. Besides, my option + up is not working probably for my system setting. Could we make it customizable?

**Comment by jmbenedetto** [comment]
Hello. Same here. MacOS 15.5. Lovely MindMap 1.0.3
Option + directional keys not working. Entre and Shift + Enter has the same effect (new line).
I looked for errors in console, but could'n find any.
If you'd be available, we can do a screen sharing exercise.

Thanks for the extension,

**Comment by shaunhurryup** [comment]
The hotkey conflict problem has been fixed #19, please update to version 1.0.4 to experience it. Sorry for replying so late 😹
