### ISSUE TITLE
仅在启用插件的第一次使用生效

### ISSUE THREAD

**Issue by Macr0phag3** [xincan1949/lovely-mindmap#12]
Obsidian Version 1.6.3 (Installer 1.5.12) in macos

问题如题所示。

复现过程：

1. 打开 Obsidian sandbox vault，避免其他插件的干扰
2. 安装本插件
3. 启用插件后，新建 canvas，通过 tab 可以正常新建一个节点
4. 关闭这个 canvas
5. 再次打开这个 canvas，发现 tab 不能正常新建一个节点，会变成选中上面的按钮：
<img width="434" alt="图片" src="https://github.com/shaunhurryup/lovely-mindmap/assets/20874963/f4a39f1d-ce9f-489d-873d-40e53099dea2">

6. 这个时候，如果关闭插件，再次启用，然后再次打开这个 canvas，则又可以恢复使用。

**Comment by shaunhurryup** [comment]
感谢反馈。近期会修复该问题

**Comment by shaunhurryup** [comment]
@Macr0phag3 你好，问题已修复。可以下载插件最新版本 `1.0.3` 体验下

**Comment by Macr0phag3** [comment]
另外歪个楼，我不太会写 Obsidian 的插件，是否有办法通过下述语法：

    ```graph-view
    ```

或者 `<graph-view></graph-view>`

来在任意页面中嵌入全局或者局部关系图谱？

如果你愿意开发这个插件的话，我愿意它付费。

**Comment by shaunhurryup** [comment]
Obsidian 作为闭源软件，它的插件 API 文档和说明做得很差，能劝退很多开发者

你提到的在页面中嵌入关系图谱，[官方团队好像没把 graph view 的 API 暴露出来](https://forum.obsidian.md/t/graph-rendering-api/73378#:~:text=Graph%20view%20is%20a%20very%20complicated%20plugin%20internally%2C%20which%20is%20why%20there%20is%20no%20API%20currently%2C%20and%20there%20might%20never%20be%20one.)，真是那样的话就不好搞了

不太清楚往页面插入关系图谱的目的是什么？通过二维视角把几篇文章/画板连接到一起吗？

倒是有开发者做了个类似[关系图谱](https://github.com/HEmile/juggl)的插件，可以关注下
