### ISSUE TITLE
似乎与tasks插件存在冲突

### ISSUE THREAD

**Issue by ongiei-ab** [xincan1949/lovely-mindmap#14]
Obsidian Version 1.6.5 (Installer 1.6.5) in windows

问题如题，在与tasks（版本7.6.1）同时启用时，lovely mindmap快捷键失效（tab/enter）。

复现：
打开沙箱，仅安装tasks和lovely mindmap插件，创建md文件，添加tasks任务，快捷键失效。
建立空白库测试，结果同上。

似乎是tasks版本的问题，老版本的tasks（5.4.0）与lovelymindmap共存没有该问题

**Comment by shaunhurryup** [comment]
感谢反馈，最近会抽空看下快捷键冲突的问题

**Comment by ongiei-ab** [comment]
又测试了一下，enter是正常的，只有tab会变成切换编辑选项而不是创建子节点

**Comment by shaunhurryup** [comment]
快捷键冲突问题已经修复，请更新至 1.0.4 版本 #19 体验。抱歉这么晚才回复😹
