### ISSUE TITLE
Should it work?

### ISSUE THREAD

**Issue by Blush** [xincan1949/lovely-mindmap#15]
I have no clue how to start the work. 
But with the enabled plugin, I opened the canwas and it seems does not work with expected functions.

**Comment by shaunhurryup** [comment]
Thank you for your feedback

1. Create a new canvas
2. Double-click the mouse on the canvas to create a node
3. Press `F` to focus on a node
4. Press `Tab` to create a child node
5. Press `Enter` to create a sibling node
