### ISSUE TITLE
Android系统快捷键失效

### ISSUE THREAD

**Issue by Cyletix** [xincan1949/lovely-mindmap#18]
设备：三星Galaxy Tab S8+
系统版本：Android14 
OneUI版本：6.0

Tab: 在焦点为文本框时正常工作，焦点为文本时无效
Enter: 在焦点为文本框时正常工作，焦点为文本时无效
cmd+Esc: 无效，会触发系统退出输入法, 再次按下会退出obsidian。尝试了所有Esc和功能键的组合，都无效。
opt+arrow: 在焦点为文本框时无效，在焦点为文本时会触发键盘功能快捷键Home End

如果我尝试点击其他空白位置来退出文本焦点，这是不行的，因为单击会在对应位置创建新的文本框，并且焦点仍然在新的文本上。也就是说，一旦焦点进入了文本内容，我很难再退出，键盘任何操作都无法退出，只能长按尝试移动文本框，但有时会触发文本框的编辑菜单

这似乎是个通病，我试过所有mindmap快捷键插件都有这个问题，感觉问题比较复杂，并不指望能够解决，但希望提供的信息有帮助

**Comment by Cyletix** [comment]
另外，我不清楚具体的工作机制，但看起来不同层级内容的快捷键也会有冲突，tab键在Android系统的obsidian应用中会导致焦点在UI界面元素间移动。在系统层级，alt+tab键会导致焦点在应用和分屏间切换。在canvas tab中，tab又会触发插件快捷键。

**Comment by shaunhurryup** [comment]
快捷键冲突问题已经修复，请更新至 1.0.4 版本 #19  体验。如果有更好的建议欢迎反馈，这条我先关了哈
