### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by a13ph** [xincan1949/lovely-mindmap#2]
This plugin does not seem to work on Windows at all. The only change after installation is addition of plugin settings. No hotkeys are available, no behaviour listed in README is present when editing a canvas.

Tested on Windows 10 Pro 22H2

**Comment by xincan1949** [comment]
Sad to hear that🥲
Neither `Tab` nor `Enter` work either? I tried in Window10 and it was good.

If you create canvas file first time, you should double click view to create a node.
Then click outside the node, and click the node again. The purpose of this step is to get you to switch from creation mode to navigation mode.
And then try it out by `Tab`?

**Comment by xincan1949** [comment]
Please feel free to open issue if you have any questions~
