### ISSUE TITLE
cmd 和 opt

### ISSUE THREAD

**Issue by Larry-Louis** [xincan1949/lovely-mindmap#5]
一个小问题，cmd 和 opt 在 win 里是啥按键

**Comment by xincan1949** [comment]
- cmd(command) 对应 win 的 ctl(control)
- opt(option) 对应 win 的 alt(alternate)

**Comment by Larry-Louis** [comment]
> * cmd(command) 对应 win 的 ctl(control)
> * opt(option) 对应 win 的 alt(alternate)

那我 ctrl + esc 会弹出开始菜单哎

**Comment by xincan1949** [comment]
啊是这样的，前面我对这个问题处理过，你可以在 `设置 - Hotkeys` 搜索 lovely 看到一个快捷键。
windows 建议用 Shift + Esc 替代一下～
![image](https://github.com/xincan1949/lovely-mindmap/assets/45918719/585b76c4-7d1c-4560-a81b-9a46963efec7)

**Comment by Larry-Louis** [comment]
> 啊是这样的，前面我对这个问题处理过，你可以在 `设置 - Hotkeys` 搜索 lovely 看到一个快捷键。 windows 建议用 Shift + Esc 替代一下～稍后我会在 README 中补充🙏 ![image](https://user-images.githubusercontent.com/45918719/267230557-585b76c4-7d1c-4560-a81b-9a46963efec7.png)

ok, 可以了，谢谢，加油把这个弄完善点吧，ob的canvas真的是一坨

**Comment by xincan1949** [comment]
嗯谢谢支持！主要考虑到用户数和自己平时的工作安排只开发了基础功能。有什么有趣或实用的建议也欢迎给我提意见哇

**Comment by Larry-Louis** [comment]
> 嗯谢谢支持！主要考虑到用户数和自己平时的工作安排只开发了基础功能。有什么有趣或实用的建议也欢迎给我提意见哇

嗯，说实话很多东西都还有补充的空间 :)，主要这玩意我还挺喜欢用但懒狗ob又迟迟没动作很头疼。我都在想是不是帮你这个也推进一下实用功能

**Comment by xincan1949** [comment]
可以哦～欢迎贡献 👏
